version: "3.9"
services:
  mock-tailscale:
    image: ghcr.io/joris-me/stack-coredns:master
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
    ports:
      - "8000:5000"
    environment:
      TS_NETWORK: hypothetical-anglerfish