# Variables
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"

# Build the CoreDNS base image.
build-base:
  image: docker:latest
  stage: build
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - docker:dind
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! Tag is $IMAGE_TAG"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG coredns/
    - docker push $IMAGE_TAG

test:
  stage: test
  script:
    - echo "This job tests something"

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ns1.joris.me >> ~/.ssh/known_hosts
    - ssh-keyscan ns2.joris.me >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - env
  environment: production
